# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'ProjectRequestZero' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjectRequestZero
pod 'Alamofire'
pod 'SDWebImage', '5.12.6'
end
